# -*- coding: utf-8 -*-
"""Streamlit3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Onu7ZGM0GHLIvWXHd71Bp3eK1QOlDBGt
"""

import streamlit as st
import pandas as pd

st.title("Police Incident Reports from 2018 to 2020 in San Francisco")

# Load the data from CSV
url = "https://example.com/path/to/police_reports.csv"  # Replace with the actual CSV file URL
df = pd.read_csv(url)

# Filter the data for San Francisco
df_sf = df[df['Police District'] == 'San Francisco']

# Display the filtered data in a table
st.markdown("The data shown below belongs to incident reports in the city of San Francisco, from the year 2018 to 2020, with details from each case such as date, day of the week, police district, neighborhood in which it happened, type of incident in category and subcategory, exact location and resolution.")
st.dataframe(df_sf)

# Display a map of San Francisco (assuming the DataFrame has latitude and longitude columns)
if 'Latitude' in df_sf.columns and 'Longitude' in df_sf.columns:
    st.map(df_sf[['Latitude', 'Longitude']].dropna(), zoom=12, center=(37.7749, -122.4194))
    st.markdown("Coordinates:")
    st.write(df_sf[['Latitude', 'Longitude']])
else:
    st.warning("Latitude and Longitude columns are missing in the data. Unable to display a map.")